INSERT INTO demodb.COMPUTER(CODE, BRAND) VALUES ('ABC123', 'Dell');

INSERT INTO demodb.COMPUTER(CODE, BRAND) VALUES ('ABC111', 'HP');

INSERT INTO demodb.COMPUTER(CODE, BRAND) VALUES ('ABC112', 'LG');

INSERT INTO demodb.CASHIER(CASHIER_NAME, last_name, mail, computer_id) VALUES ('Marina', 'Tribeca', 'marina@mail.com', 1);

INSERT INTO demodb.CASHIER(CASHIER_NAME, last_name, mail, computer_id) VALUES ('Rebeca', 'Morales', 'rebeca@mail.com', 2);

INSERT INTO demodb.CASHIER(CASHIER_NAME, last_name, mail, computer_id) VALUES ('Juan', 'Lopez', 'juan@mail.com', 3);

INSERT INTO demodb.CUSTOMER(CUSTOMER_NAME,ADDRESS,TAX_IDENTIFIER) VALUES ('Joe Doe', 'Springfield st. 123', '1234567');

INSERT INTO demodb.CUSTOMER(CUSTOMER_NAME,ADDRESS,TAX_IDENTIFIER) VALUES ('Ana Thompson', 'Metropolis st. 222', '1111111');

INSERT INTO demodb.CUSTOMER(CUSTOMER_NAME,ADDRESS,TAX_IDENTIFIER) VALUES ('Mara Lucas', 'Mars st. 333', '22222');

INSERT INTO demodb.PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('ARMANI CODE PARFUM 125 ML', 300.00, 'QWE342', 'Armani Code');

INSERT INTO demodb.PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('Scandal Le Parfum EDP Intense 30 Ml', 200.00, 'ABSC222', 'Scandal Le Parfum');

INSERT INTO demodb.PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('Good Girl Legere EDP 30 Ml', 230.00, 'ERTW345', 'Good Girl Legere');