//----- CREATE MAPPING JPA DB -----

CREATE TABLE IF NOT EXISTS CUSTOMER(
	CUSTOMER_ID SERIAL PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(25) NOT NULL,
	ADDRESS VARCHAR(50),
	TAX_IDENTIFIER VARCHAR(25));

CREATE TABLE IF NOT EXISTS BILL(
    CUSTOMER_ID INT(10) NOT NULL,
    CASHIER_ID INT(10) NOT NULL,
    BILL_DATE DATE,
    BILL_TOTAL DOUBLE(2),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(CASHIER_ID) REFERENCES CASHIER(CASHIER_ID),
    UNIQUE(CUSTOMER_ID, CASHIER_ID)
);

CREATE TABLE IF NOT EXISTS BILL_DETAIL(
        PRODUCT_ID INT,
        BILL_ID INT,
        QUANTITY INT(5)
        FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID)
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
        UNIQUE(BILL_ID, PRODUCT_ID)
    );

CREATE TABLE IF NOT EXISTS CASHIER(
    CASHIER_ID SERIAL PRIMARY KEY,
    CASHIER_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20),
    MAIL VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_ID SERIAL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(50),
    PRICE DOUBLE(2)
    );

CREATE TABLE IF NOT EXISTS COMPUTER(
    COMPUTER_ID SERIAL PRIMARY KEY,
    CODE VARCHAR(10) NOT NULL,
    BRAND VARCHAR(15),
    FK_CASHIER_ID UNIQUE FOREIGN KEY
    REFERENCES CASHIER(CASHIER_ID)

);
