INSERT INTO COMPUTER(CODE, BRAND) VALUES ('ABC111', 'Dell');
INSERT INTO COMPUTER(CODE, BRAND) VALUES ('ABC112', 'HP');
INSERT INTO COMPUTER(CODE, BRAND) VALUES ('ABC113', 'Apple');
INSERT INTO COMPUTER(CODE, BRAND) VALUES ('ABC114', 'Apple');
INSERT INTO COMPUTER(CODE, BRAND) VALUES ('ABC115', 'LG');
INSERT INTO COMPUTER(CODE, BRAND) VALUES ('ABC116', 'Apple');

INSERT INTO CASHIER(CASHIER_NAME, last_name, mail, status, computer_id) VALUES ('Marina', 'Tribeca', 'marina@mail.com', false, 1);
INSERT INTO CASHIER(CASHIER_NAME, last_name, mail, status, computer_id) VALUES ('Rebeca', 'Morales', 'rebeca@mail.com', false,  2);
INSERT INTO CASHIER(CASHIER_NAME, last_name, mail, status, computer_id) VALUES ('Juan', 'Lopez', 'juan@gmail.com', false, 3);
INSERT INTO CASHIER(CASHIER_NAME, last_name, mail, status, computer_id) VALUES ('Walter', 'Conde', 'walter@gmail.com', false, 4);
INSERT INTO CASHIER(CASHIER_NAME, last_name, mail, status, computer_id) VALUES ('Ulises', 'Nelson', 'ulises@mail.com', false, 5);
INSERT INTO CASHIER(CASHIER_NAME, last_name, mail, status, computer_id) VALUES ('Tamara', 'Arce', 'tamara@gmail.com', false, 6);

INSERT INTO CUSTOMER(CUSTOMER_NAME,ADDRESS,IDENTIFIER, MAIL) VALUES ('Joe Doe', 'Springfield st. 123', '1234567', 'joe@mail.com');
INSERT INTO CUSTOMER(CUSTOMER_NAME,ADDRESS,IDENTIFIER, MAIL) VALUES ('Ana Thompson', 'Metropolis st. 222', '1111111', 'ana@mail.com');
INSERT INTO CUSTOMER(CUSTOMER_NAME,ADDRESS,IDENTIFIER, MAIL) VALUES ('Mara Lucas', 'Mars st. 333', '1111112', 'mara@mail.com');

INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('PRADA', 305.00, 'PRA111', 'Prada Paradoxe');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('CHANNEL',  310.00, 'CHA111', 'Coco Mademoiselle le eau privée');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('DIOR', 240.00, 'DIO111', 'Miss Dior');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('MUGLER', 270.00, 'MUG111', 'Alien');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('PACO RABANNE', 230.00, 'PAC111', 'Fame Blooming Pink');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('CAROLINA HERRERA', 225.00, 'CAR111', 'Good Girl Legere');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('HUGO BOSS', 290.00, 'HUG111', 'Boss Bottled Pacific');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('DIOR', 230.00, 'DIO112', 'Sauvage Elixir');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('CHANNEL', 250.00, 'CHA112', 'Bleu de Chanel');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('PACO RABANNE', 280.00, 'PAC112', 'Invictus');
INSERT INTO PRODUCT(DESCRIPTION, PRICE, PRODUCT_CODE, PRODUCT_NAME) VALUES('CHANNEL', 300.00, 'CHA113', 'Allure Homme Sport');